name: FTP-Deploy
on:
  push:
    branches:
      - deploy-production

jobs:
  deploy:
    name: Build and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0 
        with:
          server: land-interior.sakura.ne.jp
          port: 22
          username: land-interior
          password: land0000
          server-dir: "/home/land-interior/www/website"
          exclude: "[static]"

