name: Deploy via Github Actions to Production
on:
  push:
    branches:
      - deploy-production
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'

jobs:
  test:
    name: Deploy to server

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        env:                                        
          FTP_SERVER: ${{ secrets.FTP_SERVER }}:${{ secrets.FTP_PORT }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: "/home/land-interior/www/website/"
#           exclude: "[static, **/.**/**, .gitignore,  **/.git/**, **/node_modules/**, **/vendor/**, .editorconfig, README.md, .phpcs.xml.dist, **.json, **.lock, postcss.config.js, **/src/**]"
